pragmatic:
  completeLabeling:
    enabled: true
  edgeCrossing:
    enabled: true
  sourcesAndSinks:
    enabled: true
    maxStartEvents: 1
    maxEndEvents: 1
  taskTypeDefinition:
    forbiddenTaskTypes: manualTask,task,scriptTask